-- Crear usuario
CREATE USER IF NO EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';

-- DARLE PRIVILEGIOS AL USUARIO
GRANT ALL PRIVILEGES ON *.* TO 'user_0d_1'@'localhost';

-- RECARGAR LOS PRIVILEGIOS EN EL SERVIDOR
FLUSH PRIVILEGES;